"""your migration message

Revision ID: 09b5dc2f49db
Revises: 2082f227c9f9
Create Date: 2025-07-09 12:59:30.406793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09b5dc2f49db'
down_revision: Union[str, None] = '2082f227c9f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # op.drop_table('alembic_version')
    # op.add_column('financement', sa.Column('type', sa.Enum('PERSONNEL', 'PARRAINAGE', 'INTERNE', name='typefinancement', schema='gestion_missions'), nullable=False), schema='gestion_missions')
    # op.add_column('missions', sa.Column('type', sa.Enum('NATIONALE', 'INTERNATIONALE', name='typemission', schema='gestion_missions'), nullable=True), schema='gestion_missions')
    # op.add_column('ordres_mission', sa.Column('etat', sa.Enum('OUVERTE', 'EN_ATTENTE', 'VALIDEE_HIERARCHIQUEMENT', 'VALIDEE_BUDGETAIREMENT', 'APPROUVEE', 'CLOTUREE', 'REFUSEE', name='etatmission', schema='gestion_missions'), nullable=True), schema='gestion_missions')
    # op.add_column('remboursement', sa.Column('etat', sa.Enum('OUVERTE', 'EN_ATTENTE', 'VALIDEE_HIERARCHIQUEMENT', 'VALIDEE_BUDGETAIREMENT', 'APPROUVEE', 'CLOTUREE', 'REFUSEE', name='etatmission', schema='gestion_missions'), nullable=True), schema='gestion_missions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('remboursement', 'etat', schema='gestion_missions')
    # op.drop_column('ordres_mission', 'etat', schema='gestion_missions')
    # op.drop_column('missions', 'type', schema='gestion_missions')
    # op.drop_column('financement', 'type', schema='gestion_missions')
    # ### end Alembic commands ###
