"""second migration

Revision ID: 09ee2549b145
Revises: 
Create Date: 2025-04-08 15:23:50.606476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ee2549b145'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS gestion_missions")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ligne_budgetaire',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codeLigne', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('exerciceBudgetaire', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='gestion_missions'
    )
    op.create_table('missions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('NATIONALE', 'INTERNATIONALE', name='typemission'), nullable=True),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=False),
    sa.Column('pays', sa.String(), nullable=False),
    sa.Column('ville', sa.String(), nullable=False),
    sa.Column('etat', sa.Enum('OUVERTE', 'EN_ATTENTE', 'VALIDEE', 'REFUSEE', name='etatmission'), nullable=True),
    sa.Column('budgetPrevu', sa.Float(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='gestion_missions'
    )
    op.create_table('ordres_mission',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('accord_respo', sa.LargeBinary(), nullable=False),
    sa.Column('dateDebut', sa.Date(), nullable=True),
    sa.Column('dateFin', sa.Date(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('mission_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['gestion_missions.missions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gestion_missions'
    )
    op.create_table('financement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('PERSONNEL', 'PARRAINAGE', 'INTERNE', name='typefinancementenum'), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('valide', sa.Boolean(), nullable=True),
    sa.Column('devise', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('ordre_mission_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['ordre_mission_id'], ['gestion_missions.ordres_mission.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ordre_mission_id'),
    schema='gestion_missions'
    )
    op.create_table('heberegement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dateDebut', sa.Date(), nullable=True),
    sa.Column('dateFin', sa.Date(), nullable=True),
    sa.Column('localisation', sa.String(), nullable=False),
    sa.Column('typeHebergement', sa.String(), nullable=False),
    sa.Column('ordre_mission_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['ordre_mission_id'], ['gestion_missions.ordres_mission.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gestion_missions'
    )
    op.create_table('rapport_mission',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contenu', sa.String(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('ordre_mission_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['ordre_mission_id'], ['gestion_missions.ordres_mission.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ordre_mission_id'),
    schema='gestion_missions'
    )
    op.create_table('voyage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('moyen', sa.String(), nullable=True),
    sa.Column('dateVoyage', sa.Date(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('ordre_mission_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['ordre_mission_id'], ['gestion_missions.ordres_mission.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gestion_missions'
    )
    op.create_table('justificatif',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('modifiedAt', sa.DateTime(), nullable=True),
    sa.Column('financement_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['financement_id'], ['gestion_missions.financement.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gestion_missions'
    )
    op.create_table('remboursement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('etat', sa.Enum('OUVERTE', 'EN_ATTENTE', 'VALIDEE', 'REFUSEE', name='etatmission'), nullable=True),
    sa.Column('valide', sa.Boolean(), nullable=True),
    sa.Column('dateDemande', sa.Date(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('financement_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['financement_id'], ['gestion_missions.financement.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gestion_missions'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('remboursement', schema='gestion_missions')
    op.drop_table('justificatif', schema='gestion_missions')
    op.drop_table('voyage', schema='gestion_missions')
    op.drop_table('rapport_mission', schema='gestion_missions')
    op.drop_table('heberegement', schema='gestion_missions')
    op.drop_table('financement', schema='gestion_missions')
    op.drop_table('ordres_mission', schema='gestion_missions')
    op.drop_table('missions', schema='gestion_missions')
    op.drop_table('ligne_budgetaire', schema='gestion_missions')
    # ### end Alembic commands ###
