"""titre mission

Revision ID: 2f6bfc53bbd1
Revises: 887fe3637672
Create Date: 2025-05-28 15:34:46.396785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f6bfc53bbd1'
down_revision: Union[str, None] = '887fe3637672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # op.add_column('missions', sa.Column('titre', sa.String(), nullable=True), schema='gestion_missions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('missions', 'titre', schema='gestion_missions')

    # ### end Alembic commands ###
