"""report update
Revision ID: 887fe3637672
Revises: 547c6bc8bfb0
Create Date: 2025-05-27 09:36:06.160122
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '887fe3637672'
down_revision: Union[str, None] = '547c6bc8bfb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Fix: Use USING clause to convert VARCHAR to UUID
    op.alter_column('historique_validation', 'user_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False,
               schema='gestion_missions',
               postgresql_using='user_id::uuid')

    # Add new columns to rapport_mission
    # op.add_column('rapport_mission', sa.Column('objective', sa.String(), nullable=True), schema='gestion_missions')
    # op.add_column('rapport_mission', sa.Column('proceedings', sa.String(), nullable=True), schema='gestion_missions')
    # op.add_column('rapport_mission', sa.Column('resultAchieved', sa.String(), nullable=True), schema='gestion_missions')
    # op.add_column('rapport_mission', sa.Column('nextStep', sa.String(), nullable=True), schema='gestion_missions')
    # op.add_column('rapport_mission', sa.Column('keyContact', sa.String(), nullable=True), schema='gestion_missions')
    # op.add_column('rapport_mission', sa.Column('interlocutors', sa.String(), nullable=True), schema='gestion_missions')
    # op.add_column('rapport_mission', sa.Column('difficulties', sa.String(), nullable=True), schema='gestion_missions')
    # op.add_column('rapport_mission', sa.Column('recommendations', sa.String(), nullable=True), schema='gestion_missions')
    #
    # # Drop old columns
    # op.drop_column('rapport_mission', 'contenu', schema='gestion_missions')
    # op.drop_column('rapport_mission', 'data', schema='gestion_missions')
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Add back the old columns
    # op.add_column('rapport_mission', sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=True), schema='gestion_missions')
    # op.add_column('rapport_mission', sa.Column('contenu', sa.VARCHAR(), autoincrement=False, nullable=False), schema='gestion_missions')
    #
    # # Drop new columns
    # op.drop_column('rapport_mission', 'recommendations', schema='gestion_missions')
    # op.drop_column('rapport_mission', 'difficulties', schema='gestion_missions')
    # op.drop_column('rapport_mission', 'interlocutors', schema='gestion_missions')
    # op.drop_column('rapport_mission', 'keyContact', schema='gestion_missions')
    # op.drop_column('rapport_mission', 'nextStep', schema='gestion_missions')
    # op.drop_column('rapport_mission', 'resultAchieved', schema='gestion_missions')
    # op.drop_column('rapport_mission', 'proceedings', schema='gestion_missions')
    # op.drop_column('rapport_mission', 'objective', schema='gestion_missions')

    # Fix: Use USING clause to convert UUID back to VARCHAR
    op.alter_column('historique_validation', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               schema='gestion_missions',
               postgresql_using='user_id::varchar')
    # ### end Alembic commands ###