"""add montant alloue field

Revision ID: bfb75478cd57
Revises: c7b50a382b94
Create Date: 2025-09-24 18:10:59.550761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfb75478cd57'
down_revision: Union[str, None] = 'c7b50a382b94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('ordres_mission', sa.Column('montant_alloue', sa.Float(), nullable=True), schema='gestion_missions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordres_mission', 'montant_alloue', schema='gestion_missions')
    # ### end Alembic commands ###
