"""ligne_budgetaire update

Revision ID: c7b50a382b94
Revises: 09b5dc2f49db
Create Date: 2025-08-15 18:30:44.792265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7b50a382b94'
down_revision: Union[str, None] = '09b5dc2f49db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auth_schema_utilisateurs_email', table_name='utilisateurs', schema='auth_schema')
    op.drop_index('ix_auth_schema_utilisateurs_username', table_name='utilisateurs', schema='auth_schema')
    op.drop_table('utilisateurs', schema='auth_schema')
    op.drop_table('alembic_version_portal', schema='auth_schema')
    op.add_column('ordres_mission', sa.Column('ligne_budgetaire_id', sa.UUID(), nullable=True), schema='gestion_missions')
    op.create_foreign_key(None, 'ordres_mission', 'ligne_budgetaire', ['ligne_budgetaire_id'], ['id'], source_schema='gestion_missions', referent_schema='gestion_missions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ordres_mission', schema='gestion_missions', type_='foreignkey')
    op.drop_column('ordres_mission', 'ligne_budgetaire_id', schema='gestion_missions')
    op.create_table('alembic_version_portal',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_portal_pkc'),
    schema='auth_schema'
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('prenom', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nom', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('fonction', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('statut', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('unite', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('telephone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dateInscription', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='utilisateurs_pkey'),
    schema='auth_schema'
    )
    op.create_index('ix_auth_schema_utilisateurs_username', 'utilisateurs', ['username'], unique=True, schema='auth_schema')
    op.create_index('ix_auth_schema_utilisateurs_email', 'utilisateurs', ['email'], unique=True, schema='auth_schema')
    # ### end Alembic commands ###
