"""dateDebut mission

Revision ID: d03302bc350d
Revises: bfb75478cd57
Create Date: 2025-09-26 10:51:24.684722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd03302bc350d'
down_revision: Union[str, None] = 'bfb75478cd57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('dateDebut', sa.DateTime(), nullable=True), schema='gestion_missions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('missions', 'dateDebut', schema='gestion_missions')

    # ### end Alembic commands ###
