"""rapport validation column

Revision ID: daa68dc35dc1
Revises: 2f6bfc53bbd1
Create Date: 2025-05-29 11:58:25.636703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'daa68dc35dc1'
down_revision: Union[str, None] = '2f6bfc53bbd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rapport_mission', sa.Column('isValid', sa.Boolean(), nullable=True), schema='gestion_missions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rapport_mission', 'isValid', schema='gestion_missions')
    # ### end Alembic commands ###
