"""initial migration

Revision ID: eca7148abc38
Revises: 
Create Date: 2025-04-18 16:54:34.428329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eca7148abc38'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ligne_budgetaire',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codeLigne', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('exerciceBudgetaire', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='gestion_missions'
    )
    op.create_table('missions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('NATIONALE', 'INTERNATIONALE', name='typemission'), nullable=True),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=False),
    sa.Column('pays', sa.String(), nullable=False),
    sa.Column('ville', sa.String(), nullable=False),
    sa.Column('etat', sa.Enum('OUVERTE', 'EN_ATTENTE', 'VALIDEE', 'REFUSEE', name='etatmission'), nullable=True),
    sa.Column('budgetPrevu', sa.Float(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='gestion_missions'
    )
    op.create_table('ordres_mission',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('accord_respo', sa.LargeBinary(), nullable=False),
    sa.Column('dateDebut', sa.Date(), nullable=True),
    sa.Column('dateFin', sa.Date(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('mission_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['gestion_missions.missions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gestion_missions'
    )
    op.create_table('financement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('PERSONNEL', 'PARRAINAGE', 'INTERNE', name='typefinancementenum'), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('valide', sa.Boolean(), nullable=True),
    sa.Column('devise', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('ordre_mission_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['ordre_mission_id'], ['gestion_missions.ordres_mission.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ordre_mission_id'),
    schema='gestion_missions'
    )
    op.create_table('heberegement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dateDebut', sa.Date(), nullable=True),
    sa.Column('dateFin', sa.Date(), nullable=True),
    sa.Column('localisation', sa.String(), nullable=False),
    sa.Column('typeHebergement', sa.String(), nullable=False),
    sa.Column('ordre_mission_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['ordre_mission_id'], ['gestion_missions.ordres_mission.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gestion_missions'
    )
    op.create_table('rapport_mission',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contenu', sa.String(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('ordre_mission_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['ordre_mission_id'], ['gestion_missions.ordres_mission.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ordre_mission_id'),
    schema='gestion_missions'
    )
    op.create_table('voyage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('moyen', sa.String(), nullable=True),
    sa.Column('dateVoyage', sa.Date(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('ordre_mission_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['ordre_mission_id'], ['gestion_missions.ordres_mission.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gestion_missions'
    )
    op.create_table('justificatif',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('modifiedAt', sa.DateTime(), nullable=True),
    sa.Column('financement_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['financement_id'], ['gestion_missions.financement.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gestion_missions'
    )
    op.create_table('remboursement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('etat', sa.Enum('OUVERTE', 'EN_ATTENTE', 'VALIDEE', 'REFUSEE', name='etatmission'), nullable=True),
    sa.Column('valide', sa.Boolean(), nullable=True),
    sa.Column('dateDemande', sa.Date(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('financement_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['financement_id'], ['gestion_missions.financement.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gestion_missions'
    )
    op.drop_table('alembic_version_achat', schema='gestion_demande_achat')
    op.drop_table('ligne_demande', schema='gestion_demande_achat')
    op.drop_table('type_materiel', schema='gestion_demande_achat')
    op.drop_table('ligne_budgetaire', schema='gestion_demande_achat')
    op.drop_table('demande_achat', schema='gestion_demande_achat')
    op.drop_table('justificatif', schema='gestion_demande_achat')
    op.drop_table('materiel', schema='gestion_demande_achat')
    op.drop_table('validations', schema='gestion_demande_achat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('typeValidation', postgresql.ENUM('SOUMISE', 'EN_ATTENTE_VALIDATION_BUDGETAIRE', 'VALIDE_BUDGETAIREMENT', 'EN_ATTENTE_VALIDATION_HIERARCHIQUE', 'VALIDEE_HIERARCHIQUEMENT', 'EN_COURS_TRAITEMENT_SERVICE_ACHAT', 'COMMANDE_EMISE', 'EN_COURS_LIVRAISON', 'LIVREE', 'ARCHIVEE', 'REFUSEE', name='etatvalidation'), autoincrement=False, nullable=True),
    sa.Column('date_validation', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('commentaire', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('demande_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['demande_id'], ['gestion_demande_achat.demande_achat.id'], name='validations_demande_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='validations_pkey'),
    schema='gestion_demande_achat'
    )
    op.create_table('materiel',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('categorie', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('designation', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('prix_unitaire_estime', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['categorie'], ['gestion_demande_achat.type_materiel.id'], name='materiel_categorie_fkey'),
    sa.PrimaryKeyConstraint('id', name='materiel_pkey'),
    schema='gestion_demande_achat',
    postgresql_ignore_search_path=False
    )
    op.create_table('justificatif',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modifiedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('demande_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['demande_id'], ['gestion_demande_achat.demande_achat.id'], name='justificatif_demande_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='justificatif_pkey'),
    schema='gestion_demande_achat'
    )
    op.create_table('demande_achat',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dateDemande', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('etatValidation', postgresql.ENUM('SOUMISE', 'EN_ATTENTE_VALIDATION_BUDGETAIRE', 'VALIDE_BUDGETAIREMENT', 'EN_ATTENTE_VALIDATION_HIERARCHIQUE', 'VALIDEE_HIERARCHIQUEMENT', 'EN_COURS_TRAITEMENT_SERVICE_ACHAT', 'COMMANDE_EMISE', 'EN_COURS_LIVRAISON', 'LIVREE', 'ARCHIVEE', 'REFUSEE', name='etatvalidation'), autoincrement=False, nullable=True),
    sa.Column('typeDemande', postgresql.ENUM('APPEL_OFFRE', 'DEMANDE_ACHAT', 'GRE_GRE', 'ACHAT_ENLIGNE', name='typedemande'), autoincrement=False, nullable=True),
    sa.Column('priorite', postgresql.ENUM('BASSE', 'NORMAL', 'HAUTE', 'CRITIQUE', name='priorite'), autoincrement=False, nullable=True),
    sa.Column('dateBesoin', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('ligne_budgetaire_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ligne_budgetaire_id'], ['gestion_demande_achat.ligne_budgetaire.id'], name='demande_achat_ligne_budgetaire_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='demande_achat_pkey'),
    schema='gestion_demande_achat',
    postgresql_ignore_search_path=False
    )
    op.create_table('ligne_budgetaire',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('codeLigne', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nom', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('exerciceBudgetaire', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ligne_budgetaire_pkey'),
    schema='gestion_demande_achat',
    postgresql_ignore_search_path=False
    )
    op.create_table('type_materiel',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('libelle', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='type_materiel_pkey'),
    sa.UniqueConstraint('libelle', name='type_materiel_libelle_key'),
    schema='gestion_demande_achat',
    postgresql_ignore_search_path=False
    )
    op.create_table('ligne_demande',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('materiel_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('demande_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('quantite', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['demande_id'], ['gestion_demande_achat.demande_achat.id'], name='ligne_demande_demande_id_fkey'),
    sa.ForeignKeyConstraint(['materiel_id'], ['gestion_demande_achat.materiel.id'], name='ligne_demande_materiel_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ligne_demande_pkey'),
    schema='gestion_demande_achat'
    )
    op.create_table('alembic_version_achat',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_achat_pkc'),
    schema='gestion_demande_achat'
    )
    op.drop_table('remboursement', schema='gestion_missions')
    op.drop_table('justificatif', schema='gestion_missions')
    op.drop_table('voyage', schema='gestion_missions')
    op.drop_table('rapport_mission', schema='gestion_missions')
    op.drop_table('heberegement', schema='gestion_missions')
    op.drop_table('financement', schema='gestion_missions')
    op.drop_table('ordres_mission', schema='gestion_missions')
    op.drop_table('missions', schema='gestion_missions')
    op.drop_table('ligne_budgetaire', schema='gestion_missions')
    # ### end Alembic commands ###
